# version: '3.7'

# services:
#   main-api:
#     build:
#       context: ./
#       dockerfile: Gateway/ProductService/Dockerfile
#     restart: always
#     ports:
#       - "5000:80"

version: "3.8"
services:
    rabbitmqservice:
        container_name: rabbitmqcontainer
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest        
        image: rabbitmq:3-management
                
    productservice:
      container_name: productservicecontainer
      build:
        context: ./
        dockerfile: Gateway/ProductService/Dockerfile
      restart: on-failure
      ports:
        - "9000:80"
      depends_on:
       - rabbitmqservice       
    
    deliveggieuiapp:
      container_name: deliveggieuicontainer
      build:
        context: ./DeliVeggieUIApp
        dockerfile: Dockerfile
      restart: on-failure
      ports:
        - "5000:80"
      depends_on:
        - productservice       
