FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim  AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Gateway/ProductService/*.csproj ./ProductService/
COPY Gateway/Domain/*.csproj ./Domain/
COPY Gateway/Infrastructure/*.csproj ./Infrastructure/
COPY Gateway/Application/*.csproj ./Application/
COPY Gateway/DeliVeggieSharedLibrary/*.csproj ./DeliVeggieSharedLibrary/
# COPY Microservices/ProductMicroservice/*.csproj ./ProductMicroservice/
# COPY UnitTest/ProductMicroservice.UnitTest/*.csproj ./ProductMicroservice.UnitTest/

RUN dotnet restore

# copy everything else and build app
COPY Gateway/ProductService/. ./ProductService/
COPY Gateway/Application/. ./Application/
COPY Gateway/Infrastructure/. ./Infrastructure/
COPY Gateway/Domain/. ./Domain/
COPY Gateway/DeliVeggieSharedLibrary/. ./DeliVeggieSharedLibrary/

# COPY Microservices/ProductMicroservice/. ./ProductMicroservice/
# COPY UnitTest/ProductMicroservice.UnitTest/. ./ProductMicroservice.UnitTest/


WORKDIR /app/ProductService
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS runtime
WORKDIR /app

COPY --from=build /app/ProductService/out ./
ENTRYPOINT ["dotnet", "ProductService.dll"]